name: dream_note
description: A new Flutter project.
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^5.0.3
  equatable: ^2.0.5
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.19
  flutter_platform_widgets: ^3.2.0
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_whatsnew: ^1.0.5+2
  hydrated_bloc: ^9.1.0
  infinite_scroll_pagination: ^3.2.0
  keyboard_dismisser: ^3.0.0
  overlay_support: ^2.1.0
  package_info_plus: ^3.0.3
  path_provider: ^2.0.14
  simple_animations: ^5.0.0+3
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
