name: dream_note
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.19
  flutter_platform_widgets: ^3.2.0
  flutter_spinkit: ^5.1.0
  hydrated_bloc: ^9.1.0
  infinite_scroll_pagination: ^3.2.0
  overlay_support: ^2.1.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
